name: Comment on PR Opened

on:
  pull_request:
    types:
      - opened
    branches-ignore:
      - main
      - develop

jobs:
  Comment:
    # if: github.head_ref != 'main' && github.head_ref != 'develop'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment on PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Thanks for opening this PR!
